project/ToDo/urls.py
from django.urls import path
from . import views


app_name = 'todo'

urlpatterns = [
    path('', views.ShowTodo.as_view(), name='home'),
    path('detail/<slug:slug>', views.DetailTodo.as_view(), name='detail'),
    path('delete/<slug:slug>', views.DeleteTask.as_view(), name='delete'),
    path('add', views.AddTask.as_view(), name='add_task'),
    path('update/<slug:slug>', views.UpdateTodo.as_view(), name='update')
]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ToDo.urls'))
]

project/ToDo/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse


# Create your models here.


class Todo(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=100)
    description = models.TextField(null=True, blank=True, default='')
    time = models.DateTimeField(default=timezone.now)

    class   Meta:
        ordering = ('-time',)

    def __str__(self):
        return self.title

project/ToDo/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView
from django.urls import reverse_lazy
from .models import Todo
# Create your views here.


class ShowTodo(ListView):
    model = Todo
    template_name = 'todo/home.html'


class DetailTodo(DetailView):
    template_name = 'todo/detail.html'

    def get_object(self):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Todo, slug=slug)
        return obj


class DeleteTask(DeleteView):
    template_name = 'todo/delete.html'
    success_url = reverse_lazy('todo:home')

    def get_object(self):
        slug = self.kwargs.get('slug')
        obj = get_object_or_404(Todo, slug=slug)
        return obj


class AddTask(CreateView):
    model = Todo
    fields = ('title', 'slug', 'description', 'time')
    template_name = 'todo/add_task.html'
    success_url = reverse_lazy('todo:home')


class UpdateTodo(UpdateView):
    template_name = 'todo/add_task.html'
    model = Todo
    fields = ('title', 'slug', 'description', 'time')
    success_url = reverse_lazy('todo:home')

project/templates/todo/add_task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        <div class="form-group">
            <form method="post">{% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success mt-10" type="submit">Save</button>
            </form>
        </div>
    </div>
</body>
</html>

project/templates/todo/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deleting</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <form method="post">{% csrf_token %}
            <div class="text-center mt-10">
                <p class="mt-10">Are you sure you want to delete "{{ object }}"?</p>
            </div>
            <div class="text-center">
                <input class="btn btn-danger" type="submit" value="Confirm">
            </div>
        </form>
    </div>
</body>
</html>

project/templates/todo/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
    <div class="container">
        <div class="text-center mt-3">
            <h1>{{object.title}}</h1>
        </div>
        <div class="text-center mt-7">
            <p>{{object.time }}</p>
        </div>
        <div class="card">
            <div class="card-body">
                <p class="pl-10">{{object.description }}</p>
            </div>
        </div>
        <div class="text-right">
            <a class="btn btn-danger mt-15" href="{% url 'todo:delete' object.slug %}">Delete Task</a>
            <a class="btn btn-primary mt-15" href="{% url 'todo:update' object.slug %}">Update Task</a>
        </div>
    </div>
</body>
</html>

project/templates/todo/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container pt-4">
        {% for task in object_list %}
            <div class="row mt-3">
                <div class="col">
                    <h3><a href="{% url 'todo:detail' task.slug %}">{{task.title}}</a></h3>
                </div>
                <div class="col pt-2 text-right">
                    <h6>{{task.time }}</h6>
                </div>
            </div>
            <h5>{{task.description }}</h5>
            <hr>
        {% endfor %}
        <a href="{% url 'todo:add_task' %}"  class="btn btn-info float-right">Add Task</a>
    </div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</body>

</html>